# Nombre del Action
name: CI

# Cuando activamos el action
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # Jobs
  firebase-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Use Node.js 10.x
      uses: actions/setup-node@master
      with:
        node-version: '10.x'
    - name: Install dependencies
      run: yarn install
    - name: Build workspace Client
      run: yarn workspace client run  build
    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
        PROJECT_PATH: ${{ secrets.PROJECT_PATH }}
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      with:
        projectBaseDir: packages/client/src
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}